### ISSUE TITLE
[MCOMPILER-30] Compiler fork executable fails when the path has spaces

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#372]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MCOMPILER-30](https://issues.apache.org/jira/browse/MCOMPILER-30?redirect=false)** and commented

JAVA_1_3_HOME=C:\Program Files\Java\jdk1.3.1_18

    <plugin>
      <artifactId>maven-compiler-plugin</artifactId>
      <configuration>
        <fork>true</fork>
        <compilerVersion>1.3</compilerVersion>
        <executable>${JAVA_1_3_HOME}/bin/javac</executable>
      </configuration>
    </plugin>

Fails with

Failure executing javac,  but could not parse the error:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

---

**Affects:** 2.0.1

**Issue Links:**
- [MCOMPILER-79](https://issues.apache.org/jira/browse/MCOMPILER-79) Regression?: Compiler fork executable fails when the path has spaces
 (_**"is duplicated by"**_)
- [MCOMPILER-79](https://issues.apache.org/jira/browse/MCOMPILER-79) Regression?: Compiler fork executable fails when the path has spaces

- [SUREFIRE-77](https://issues.apache.org/jira/browse/SUREFIRE-77) Surefire fork fails under windows when command has several quotes

4 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Same problem, is not the path having spaces, but not quoting the full command when using a shell executable

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed upgrading plexus-compiler versions

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed in the plexus-compiler-javac again

**Comment by jira-importer** [comment]
**[Bill](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gooddeal777)** commented

I am try to use this feature by plug-in version 2.0.2 (Maven 2.0.7). I still got  the error:

Failure executing javac, but could not parse the error:
'C:\Program' is not recognized as an internal or external command,

I have tried to put  " " to enclose the value but still not working?

I checked my plugin version (2.0.2). Is this issue has been addressed in this version?

Thank you.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

reopened per user comments

**Comment by jira-importer** [comment]
**[Dan Rollo](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bhamail)** commented

He he. But how cool would that have been if it had worked?! ;)

**Comment by jira-importer** [comment]
**[Hilal Ram](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hram)** commented

I'm also facing this issue. Simply Because I have the Oracle installed on Program files and it's PATH is causing the build to fai
--- Any Quick Fix on this ???

[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure
Failure executing javac,  but could not parse the error:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.BuildFailureException: Compilation failure
Failure executing javac,  but could not parse the error:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa

ultLifecycleExecutor.java:699)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:4
1)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.

**Comment by jira-importer** [comment]
**[Hilal Ram](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hram)** commented

HOW TO FIX THIS ISSUE

---

This is how you can Quick Fix this issue...

Go to your compile plugin -- Remove the \<fork>true\</fork> Element ; the build works fine.....

    <plugin>
         <artifactId>maven-compiler-plugin</artifactId>
         <configuration>
              
              <executable>
                       ${JAVA_HOME_1.5}/bin/javac.exe
              </executable>
              <compilerVersion>1.5</compilerVersion>
              <source>1.5</source>
              <target>1.5</target>
         </configuration>
    </plugin>
    <plugin>

**Comment by jira-importer** [comment]
**[Jakob Magiera](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmagiera)** commented

`@Hilal` Ram
This doesn't solve the issue, because maven is not actually executing the javac you specified but the internal compiler of the jdk that is set in your java_home. Think about it, it doesn't make sense to specify an executable if you are not going to fork a new process.

**Comment by jira-importer** [comment]
**[Hilal Ram](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hram)** commented

This is the solution for windws (and not unix) and fork tag has no significance.

I think this is why it works Windws platforms : when you say fork = true, mvn thinks you are on unix and expect and executable path in Unix format..( I'm not sure of it, may be mvn experts can comment) and when you say fork=false (or comment it out to default to false) you are back in windws.

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

Please refer to https://cwiki.apache.org/confluence/display/MAVEN/The+Great+JIRA+Cleanup+of+2014 if you're wondering why this issue was closed out.
