### ISSUE TITLE
[MCOMPILER-22] Compilation fails: "The command line is too long."

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#386]
**[Matthew Beermann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mbeerman)** opened **[MCOMPILER-22](https://issues.apache.org/jira/browse/MCOMPILER-22?redirect=false)** and commented

For one of my project, compilation fails with the message "The command line is too long". As far as I can tell, it's listing each and every source file, one at a time, in the -sourcepath attribute. (?!?) Here's the log:

[DEBUG] Source roots:
[DEBUG]  C:\continuum-1.0.2\apps\continuum\working-directory\26\src
[DEBUG] Command line options:
[DEBUG] -d C:\continuum-1.0.2\apps\continuum\working-directory\26\target\classes -classpath \<DEPENDENCIES SNIPPED HERE> -sourcepath \<ENORMOUSLY LONG LIST OF SOURCE FILES HERE> -g -nowarn -target 1.4 -source 1.4
Compiling 167 source files to C:\continuum-1.0.2\apps\continuum\working-directory\26\target\classes
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ----------------------------------------------------------------------------
[INFO] Compilation failure

Failure executing javac,  but could not parse the error:
The command line is too long.

[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: Compilation failure
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:551)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:429)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:110)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:432)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:530)
... 16 more

---

**Affects:** 2.0, 2.0.1

**Attachments:**
- [maven-compiler-plugin.patch](https://issues.apache.org/jira/secure/attachment/12714841/maven-compiler-plugin.patch) (_6.25 kB_)
- [maven-compiler-plugin-space-fix.patch](https://issues.apache.org/jira/secure/attachment/12714847/maven-compiler-plugin-space-fix.patch) (_6.27 kB_)
- [MCOMPILER-22.patch](https://issues.apache.org/jira/secure/attachment/12714843/MCOMPILER-22.patch) (_2.01 kB_)
- [MNG-MCCOMPILER-22-maven-compiler-plugin.patch](https://issues.apache.org/jira/secure/attachment/12714849/MNG-MCCOMPILER-22-maven-compiler-plugin.patch) (_37.07 kB_)
- [MNG-MCCOMPILER-22-plexus-compilers.patch](https://issues.apache.org/jira/secure/attachment/12714848/MNG-MCCOMPILER-22-plexus-compilers.patch) (_1.95 kB_)
- [MNG-MCCOMPILER-22-plexus-compilers-noformatting.patch](https://issues.apache.org/jira/secure/attachment/12714845/MNG-MCCOMPILER-22-plexus-compilers-noformatting.patch) (_6.26 kB_)
- [plexus-compiler-javac.patch](https://issues.apache.org/jira/secure/attachment/12714842/plexus-compiler-javac.patch) (_1.69 kB_)
- [plexus-compiler-javac-1.5.2.jar](https://issues.apache.org/jira/secure/attachment/12714852/plexus-compiler-javac-1.5.2.jar) (_9.54 kB_)

**Issue Links:**
- [MCOMPILER-45](https://issues.apache.org/jira/browse/MCOMPILER-45) Command Line argument too long
 (_**"is duplicated by"**_)
- [MCOMPILER-31](https://issues.apache.org/jira/browse/MCOMPILER-31) forking to a custom compiler does not work
 (_**"is duplicated by"**_)
- [MCOMPILER-39](https://issues.apache.org/jira/browse/MCOMPILER-39) compiler:compile with fork fails on Windows
 (_**"is duplicated by"**_)

27 votes, 12 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Test for plexus-compiler-javac that makes it currently break

**Comment by jira-importer** [comment]
**[Emmanuel Venisse](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=evenisse)** commented

The files list can be put in an external files, so command line will be short : http://java.sun.com/j2se/1.4.2/docs/tooldocs/windows/javac.html#commandlineargfile

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

And it also works in 1.3 for sources (not for options) http://java.sun.com/j2se/1.3/docs/tooldocs/solaris/javac.html

So the solution is change the list of sources in the cmd line for `@filename` with the list of sources

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Can you provide a new MNG-MCCOMPILER-22-maven-compiler-plugin.patch  without all the formatting changes?
it's impossible to know what are the real changes here and what is just formatting

**Comment by jira-importer** [comment]
**[Karel Vervaeke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karel1980)** commented

There you go.  I did some of the formatting manually, so I hope I didn't make any mistakes.

**Comment by jira-importer** [comment]
**[Karel Vervaeke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karel1980)** commented

Oops, I messed up.  The file named MNG-MCCOMPILER-22-plexus-compilers-noformatting.patch
should be called MNG-MCCOMPILER-22-maven-compiler-plugin-noformatting.patch

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Updated patches, but I don't like this solution.
As I said options can't be used as it's not supported in 1.3

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

Sun's 1.3.1_18 seems to support it:

/opt/jdk1.3.1_18/bin/javac `@opts` `@src`

with

opts content: -target 1.3
and src content: X.java

executes successfully and reads each line in content and src.

/opt/jdk1.3.1_18/bin/java -version
java version "1.3.1_18"
Java(TM) 2 Runtime Environment, Standard Edition (build 1.3.1_18-b01)
Java HotSpot(TM) Client VM (build 1.3.1_18-b01, mixed mode)

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

but it's not in the docs of 1.3, so it may be non standard

**Comment by jira-importer** [comment]
**[Karel Vervaeke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=karel1980)** commented

`@options` also works on jdk131_08 (this does, of course, not affect the point about it not being documented)

**Comment by jira-importer** [comment]
**[Jeroen Bleijenbergh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=license35)** commented

IBM jikes seems to support the same option:

C:\jikes-1.22\bin>jikes -bootclasspath c:\j2sdk1.4.2_10\jre\lib\rt.jar `@sources`.txt compiles...

This option is really a 'must' since it is impossible to compile a reasonable amount of sources using a forked compiler.

**Comment by jira-importer** [comment]
**[Jeroen Bleijenbergh](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=license35)** commented

Also: The GCJ team documented the feature

GCJ(1)                                GNU                               GCJ(1)

NAME
gcj - Ahead-of-time compiler for the Java language

SYNOPSIS
gcj [-Idir...] [-d dir...]
[--classpath=path] [--CLASSPATH=path]
[-foption...] [--encoding=name]
[--main=classname] [-C]
[-Wwarn...] [-Dname[=value]...]
sourcefile...

DESCRIPTION
As "gcj" is just another front end to "gcc", it supports many of the
same options as gcc.    This manual only documents the options specific
to "gcj".

OPTIONS
Input and output files
...

       @file
           A file containing a whitespace-separated list of input file names.
           (Currently, these must all be ".java" source files, but that may
           change.)  Each named file is compiled, just as if it had been on
           the command line.
    
       library.a

...

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

And actually, it is documented:

http://java.sun.com/j2se/1.3/docs/tooldocs/solaris/javac.html
http://java.sun.com/j2se/1.3/docs/tooldocs/win32/javac.html

referred from
http://java.sun.com/j2se/1.3/docs/tooldocs/tools.html and http://java.sun.com/j2se/1.3/docs/tooldocs/findingclasses.html

**Comment by jira-importer** [comment]
**[Andreas Guther](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aguther)** commented

Hi,

is this patch already applied and maybe available with a SNAPSHOT version?

Andreas

**Comment by jira-importer** [comment]
**[Brahim Bakayoko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brah_bak)** commented

I have fixed this bug some time ago.
Sorry if I did not post the fix early enough.

Copy the jar file to:
{local maven repository folder}\org\codehaus\plexus\plexus-compiler-javac\1.5.2

That's it.

Question: How do I submit the fix the the main development branch?

**Comment by jira-importer** [comment]
**[Allan Shoup](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=9gaqfk802@sneakemail.com)** commented

After applying the maven-compiler-plugin.patch file submitted on June 12th, a build will fail if the project's path contains a space. The attached maven-compiler-plugin-space-fix.patch file will correct the problem (tested on a windows XP OS).

**Comment by jira-importer** [comment]
**[Chris Byrd](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=byrch)** commented

It looks like these are exactly the same problem, where the compiler is trying to feed way too much information on the command line.  Does anyone have an idea about an official released fix for this?

**Comment by jira-importer** [comment]
**[Chris Byrd](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=byrch)** commented

Can anyone point me to documentation on how I go about applying the maven patches?  I can't seem to find anything in the maven site.  Also, I'm not sure in which order or what files I actually need to use in the attachments listed for this issue.  Any direction would be greatly appreciated.

In the comment above, I was linking this issue to PLX-314.  I didn't realize the comment would just be dumped in the main area.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Breahim, please send a patch

Check "Creating and submitting a patch"
http://maven.apache.org/guides/development/guide-m2-development.html

**Comment by jira-importer** [comment]
**[Chris Byrd](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=byrch)** commented

Thanks for the link, but I am still having issues.  I will describe my steps below, and the issues that arose in each respective step.

1) I downloaded the jar file sent by Brahim Bakayoko.  I then replaced the jar file in my local repository for the plexus-compiler-javac artifact.
   -  Issue: Just as Allan Shoup described, the fix provided by Brahim fails if there is a space in your path.  This did not occur before the change.

2) Allan provided a patch to the maven-compiler-plugin, to fix the failure when you have a space in the path.  I went to https://svn.apache.org/repos/asf/maven/plugins/trunk/maven-compiler-plugin and checked out the most recent source code.  
   - Issue: I tried to clean compile the code, and I received an error.  The code depends on the maven-plugins parent pom, version 8-SNAPSHOT.  I looked for it in the central repository and http://snapshots.repository.codehaus.org/, but didn't find it.  I finally found a link to plugin snapshots at http://cvs.apache.org/maven-snapshot-repository.

3) I added the http://cvs.apache.org/maven-snapshot-repository repository to the recently checked out maven-compiler-plugin code and tried the clean compile again.
   - Issue: Aparently there are the 2-SNAPSHOT and 4-SNAPSHOT versions of the code in this repository, but not the 8-SNAPSHOT.  Once again, I don't have the necessary dependencies to do the build.

4) I edited the pom.xml of the recently checked out maven-compiler-plugin source code, and changed the parent dependency from 8-SNAPSHOT to 4-SNAPSHOT.
   - Issue: This did resolve the dependency and download the 4-SNAPSHOT artifact, so the build could continue.  However, when I issued a mvn test command, the unit tests failed.

5) In the spirit of just trying things, I decided to skip the tests and just apply the patch and install.  I applied Allan Shoup provided successfully.  I then skipped the unit tests and installed the maven-compiler-plugin as the 2.1-SNAPSHOT it has listed in the code.
   - Issue: This might be where I am going wrong here.  Should I not check out the code from the trunk here?  I guess I should check out the tagged 2.0.2 version instead.

6) The patch went in successfully.  I installed the maven-compiler-plugin, edited my original project pom to use the new maven-compiler plugin 2.1-SNAPSHOT and tried a clean compile.
   - Issue: I got a new error message, but things were still the same, I couldn't complete the build when forking to a new JDK.

[INFO] [compiler:compile]
[INFO] Os is :windows xp
[INFO] Total # of java files for compilation are 25
[INFO] Compiling 1 source file to D:\Documents and Settings\xfxc104\My Documents
\Dev\workspace\pw-qis\pw-qis-core\target\classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

Failure executing javac,  but could not parse the error:
javac: invalid argument: D:\Documents and Settings\xfxc104\My Documents\Dev\work
space\pw-qis\pw-qis-core\classes
Usage: javac \<options> \<source files>

Summary:

---

Can anyone give me some hints as to where to go from here.  I'm looking at the attachments above, and I only used 2 of the 8 up there.  I don't know if I am supposed to use all of them, only some of them, and in what order am I supposed to use them.  I'm sure all of this seems quite mundane to those of you who perform these activities every day, but I assure you the process is far from clear for me.  Any help you can provide is greatly appreciated.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed in PLX-314

**Comment by jira-importer** [comment]
**[Chris Byrd](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=byrch)** commented

So this time I did step 1, then in step 2 I downloaded the source code from the maven-compiler-plugin-2.0.1 tag.  That made things considerably easier.  From what I can see on this page, it says the fix version is 2.0.2, I assume that is the version these fixes will be going into, eventually.

From that point I was able to apply Allan's patch (maven-compiler-plugin-space-fix.patch) and install the new version of the maven-compiler-plugin version 2.0.1 to my local repository.

I went back to my original project and did another clean compile.  This time I am back to the problem where there are spaces in the compiler options, so the compile fails.  The error message is below.

---

[DEBUG] Command line options:
[DEBUG] -d D:\Documents and Settings\xfxc104\My Documents\Dev\workspace\pw-qis\p
w-qis-core\target\classes `@D`:\Documents and Settings\xfxc104\My Documents\Dev\wo
rkspace\pw-qis\pw-qis-core\target\classes/options -classpath options; -g -nowarn
-target 1.3
Compiling 1 source file to D:\Documents and Settings\xfxc104\My Documents\Dev\wo
rkspace\pw-qis\pw-qis-core\target\classes
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

Failure executing javac,  but could not parse the error:
javac: invalid argument: D:\Documents
Usage: javac \<options> \<source files>

---

After all that I am back to the original question, what patches am I supposed to apply, and in what order do I apply them?  Any help is greatly appreciated.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

To use it you just need to set the version of the plugin to 2.1-SNAPSHOT and add the apache snapshot repo

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

There's still a problem to be fixed, argument files don't accept the -J options that we are using for Xmx and Xms

http://java.sun.com/j2se/1.4.2/docs/tooldocs/windows/javac.html

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Fixed by using Xmx and Xms only when forking

**Comment by jira-importer** [comment]
**[GenDyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gendyn)** commented

I am having the same problem as mentioned in this Jira issue. I have downloaded the patch and installed gnu Win32 tool.

I don't have any experience with maven as well as installing patches into a plugin. Can someone please give me the step-by-step process for the upgrade?

Thank you.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

you need to use the 2.0.2 version of the compiler plugin, no patches or anything like that, ask in the mailing list if you need help http://maven.apache.org/users/getting-help.html

**Comment by jira-importer** [comment]
**[David Biesack](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=djb)** commented

On a slightly related note, our javac builds in Maven (using v 2.3.2 of the compiler plugin) was failing
with a similar error

[INFO] Compilation failure
error: error reading /u/sasdjb/.m2/repository/com/sas/commons/lang/sas.commons.lang/1.1-SNAPSHOT/sas.commons.lang-1.1-SNAPSHOT.jar; line too long

It was unrelated to this old and fixed problem, but I want to add a note here since a web search for
my problem lead me here, and there were no other hints. So this may help others who search for
"compilation failure" and "error reading" and "line too long"

My problem turned out to be due to a bad (manual) MANIFEST.MF created in a dependent jar's maven build.
(we require specific manifest entries not created by default)
I fixed the MANIFEST.MF generation and rebuilt it, and this solved the javac error. javac was not
complaining about the command line being too long, but about a line in the MANIFEST.MF file in the jar
being too long -- although it does not say that.
