### ISSUE TITLE
[MCOMPILER-31] forking to a custom compiler does not work

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#387]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** opened **[MCOMPILER-31](https://issues.apache.org/jira/browse/MCOMPILER-31?redirect=false)** and commented

The following configuration will fail:

plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-compiler-plugin\</artifactId>
\<configuration>
\<fork>true\</fork>
\<compiler-version>1.3\</compiler-version>
\<executable>C:/temp/java/bin/javac.exe\</executable>
\<target>1.3\</target>
\</configuration>
\</plugin>

like this:

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

Failure executing javac,  but could not parse the error:

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.BuildFailureException: Compilation failure
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:555)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:47
5)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.jav
a:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:505)
at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:111)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 13 seconds
[INFO] Finished at: Fri Apr 07 14:02:37 CEST 2006
[INFO] Final Memory: 4M/8M
[INFO] --------------------------------------------------------------------

---

**Affects:** 2.0.1

**Issue Links:**
- [MCOMPILER-22](https://issues.apache.org/jira/browse/MCOMPILER-22) Compilation fails: "The command line is too long."
 (_**"duplicates"**_)

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

The current snapshot displays an informing errormessage, so this issue is a duplicate of MCOMPILER-22

**Comment by jira-importer** [comment]
**[David J. M. Karlsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** commented

Duplicates MCOMPILER-22
