### ISSUE TITLE
[MCOMPILER-64] "mvn clean install" crashes with java.lang.OutOfMemoryError: PermGen space after update to java 1.6.0_04

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#415]
**[Joern Huxhorn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=huxi)** opened **[MCOMPILER-64](https://issues.apache.org/jira/browse/MCOMPILER-64?redirect=false)** and commented

After upgrading to java 1.6.0_04 i can't build a big multi-module project anymore.
java.exe keeps allocating more and more memory (ca. 260MB) until it crashes with an error like the following:
Failure executing javac, but could not parse the error:

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: PermGen space
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at org.codehaus.plexus.compiler.javac.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:56)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
at com.sun.tools.javac.comp.Annotate.\<init>(Annotate.java:52)
at com.sun.tools.javac.comp.Annotate.instance(Annotate.java:36)
at com.sun.tools.javac.jvm.ClassReader.\<init>(ClassReader.java:215)
at com.sun.tools.javac.jvm.ClassReader.instance(ClassReader.java:168)
at com.sun.tools.javac.main.JavaCompiler.\<init>(JavaCompiler.java:293)
at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:72)
at com.sun.tools.javac.main.Main.compile(Main.java:340)
at com.sun.tools.javac.main.Main.compile(Main.java:279)
at com.sun.tools.javac.main.Main.compile(Main.java:270)
at com.sun.tools.javac.Main.compile(Main.java:87)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:420)
at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:141)
at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:493)
at org.apache.maven.plugin.TestCompilerMojo.execute(TestCompilerMojo.java:102)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)

Executing the same command with this setup
Maven version: 2.0.8
Java version: 1.5.0_13
OS name: "windows xp" version: "5.1" arch: "x86" Family: "windows"
works perfectly. java.exe allocates at most 110MB.

Increasing the PermGen space using -XX:MaxPermSize=512M didn't help, either...

This is probably a java regression introduced with j6u4 but it could also be a problem in org.codehaus.plexus.compiler.javac.IsolatedClassLoader.
I didn't experience any other problems with the new java version, so far.

---

6 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Michael Semb Wever](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michaelsembwever)** commented

I get this too. Know of no workaround.

**Comment by jira-importer** [comment]
**[asgeirn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=asgeirn)** commented

Same problem here.  I'm running with -XX:MaxPermSize=128m.

java version "1.6.0_06"
Java(TM) SE Runtime Environment (build 1.6.0_06-b02)
Java HotSpot(TM) Server VM (build 10.0-b22, mixed mode)

Maven version: 2.0.9
Java version: 1.6.0_06
OS name: "sunos" version: "5.10" arch: "x86" Family: "unix"
build	09-May-2008 13:00:08	The system is out of resources.
build	09-May-2008 13:00:08	Consult the following stack trace for details.
build	09-May-2008 13:00:08	java.lang.OutOfMemoryError: PermGen space
build	09-May-2008 13:00:08		at java.lang.ClassLoader.defineClass1(Native Method)
build	09-May-2008 13:00:08		at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
build	09-May-2008 13:00:08		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
build	09-May-2008 13:00:08		at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
build	09-May-2008 13:00:08		at java.net.URLClassLoader.access$000(URLClassLoader.java:56)
build	09-May-2008 13:00:08		at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
build	09-May-2008 13:00:08		at java.security.AccessController.doPrivileged(Native Method)
build	09-May-2008 13:00:08		at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
build	09-May-2008 13:00:08		at org.codehaus.plexus.compiler.javac.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:56)
build	09-May-2008 13:00:08		at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
build	09-May-2008 13:00:08		at com.sun.tools.javac.main.JavaCompiler.\<init>(JavaCompiler.java:314)
build	09-May-2008 13:00:08		at com.sun.tools.javac.main.JavaCompiler.instance(JavaCompiler.java:72)
build	09-May-2008 13:00:08		at com.sun.tools.javac.main.Main.compile(Main.java:340)
build	09-May-2008 13:00:08		at com.sun.tools.javac.main.Main.compile(Main.java:279)
build	09-May-2008 13:00:08		at com.sun.tools.javac.main.Main.compile(Main.java:270)
build	09-May-2008 13:00:08		at com.sun.tools.javac.Main.compile(Main.java:87)
build	09-May-2008 13:00:08		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build	09-May-2008 13:00:08		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
build	09-May-2008 13:00:08		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
build	09-May-2008 13:00:08		at java.lang.reflect.Method.invoke(Method.java:597)
build	09-May-2008 13:00:08		at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:420)
build	09-May-2008 13:00:08		at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:141)
build	09-May-2008 13:00:08		at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:493)
build	09-May-2008 13:00:08		at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
build	09-May-2008 13:00:08		at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
build	09-May-2008 13:00:08		at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
build	09-May-2008 13:00:08		at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
build	09-May-2008 13:00:08		at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
build	09-May-2008 13:00:08		at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
build	09-May-2008 13:00:08		at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
build	09-May-2008 13:00:08		at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
build	09-May-2008 13:00:08		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Could you provide us a reproducible test case?

**Comment by jira-importer** [comment]
**[Steinar Bang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=steinarb)** commented

I upgraded to maven 2.0.9, but the problem persisted.

I found this link
http://mail-archives.apache.org/mod_mbox/tuscany-dev/200809.mbox/%3C4B0CE5F4FC974DDC988FB01812E54E88@rfengt60p%3E
and changed MAVEN_OPTS from
-Xmx512m
to
-Xmx512m -XX:MaxPermSize=384m

And the problem went away.

**Comment by jira-importer** [comment]
**[Werner Mueller](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=werner.mueller@mimacom.ch)** commented

the docs mention some options to adjust memory settings for the compiler:
http://maven.apache.org/plugins/maven-compiler-plugin/examples/compile-with-memory-enhancements.html

but i dont know if its working :)

**Comment by jira-importer** [comment]
**[Barrie Treloar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=baerrach)** commented

Did you try setting MAVEN_OPTS to include -XX:MaxPermSize=512M?

e.g on the command line use
set MAVEN_OPTS=-Xmx512M -XX:MaxPermSize=512M

If that works promote it to a permanent environment variable

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

IMHO related to PLXCOMP-202
