### ISSUE TITLE
[MCOMPILER-95] no such compiler 'javac' when compiling code with maven-compiler-plugin maven 2.1.0-M1 in windows Vista 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#431]
**[Ganesh Gowtham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ganesh.gowtham)** opened **[MCOMPILER-95](https://issues.apache.org/jira/browse/MCOMPILER-95?redirect=false)** and commented

Hi Folks ,

Thanks for your great work .

when running mvn install i am getting the following error

JAVA_HOME and maven\bin in PATH is properly set .

Maven download's all pom's and jars but compilation fails .Even i had used Cygwin compilation fails with  **no such compiler 'javac'**.

infact i can able to compile java code from command line also .

Below is the stach trace with -e option .

```
D:\SVN-Projects\gt> mvn install -e  
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building my sample prj
[INFO]    task-segment: [install]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources]
[INFO] Using default encoding to copy filtered resources.
[INFO] [compiler:compile]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
 
[INFO] ------------------------------------------------------------------------
[INFO] No such compiler 'javac'.
[INFO] ------------------------------------------------------------------------
 
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: No such compiler 'javac.
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefultLifecycleExecutor.java:701)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLfecycle(DefaultLifecycleExecutor.java:538)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaltLifecycleExecutor.java:517)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHadleFailures(DefaultLifecycleExecutor.java:369)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmets(DefaultLifecycleExecutor.java:330)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLfecycleExecutor.java:181)
       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
       at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpljava:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:585)
       at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
       at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
       at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430
       at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: No such compiler 'javac'.
       at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompileMojo.java:271)
       at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:114)
       at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugnManager.java:458)
       at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefultLifecycleExecutor.java:676)
       ... 16 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Fri Mar 27 11:16:24 GMT 2009
[INFO] Final Memory: 6M/12M
[INFO] ------------------------------------------------------------------------
```

From the maven site i can to know i need to cygwin for some versions of windows , but still i am getting the same error .
infact i can able to complie the code through command prompt .

i download maven plugin for eclipse (gannymede) , after creating the same app , when mvn install i am getting same no such compiler 'javac'.

for your ref i amusing below lines in pom.xml

```xml
<plugin>   
   <artifactId>maven-compiler-plugin</artifactId>   
      <configuration>   
          <source>1.5</source>   
           <target>1.5</target>   
     </configuration>   
</plugin>
```

Please help me in resolving issue .

---

**Affects:** 2.0

**Attachments:**
- [compilation.log](https://issues.apache.org/jira/secure/attachment/12714880/compilation.log) (_26.91 kB_)

**Issue Links:**
- [MCOMPILER-96](https://issues.apache.org/jira/browse/MCOMPILER-96) compilation issue in maven 1.2.0-M1 in windows Vista no such compliler 'javac'
 (_**"is duplicated by"**_)

**Comment by jira-importer** [comment]
**[Ganesh Gowtham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ganesh.gowtham)** commented

Sorry to say it is typo i used **apache-maven-2.1.0-M1**

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

> JAVA_HOME and maven\bin in PATH is properly set .

It would be helpful to know whether the JAVA_HOME used to run Maven actually points at a JDK or just a JRE.

Please run "mvn install -X > debug.log" and attach the resulting log for further analysis, when possible using the latest Maven release version 2.1.0.

In the meantime, you could try setting the plugin's [fork](http://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#fork) parameter to `true`.

**Comment by jira-importer** [comment]
**[Ganesh Gowtham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ganesh.gowtham)** commented

pls find the compilation.log which i grabbed by executing mvn -X install -e

**Comment by jira-importer** [comment]
**[Ganesh Gowtham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ganesh.gowtham)** commented

HI Benhamin ,

i can able to compile my java code in command promt and can run the program also .

JAVA_HOME points JDK .

even when i execute in cygwin i got the same issue .

D:\SVN-Projects\gt>mvn -version
Maven version: 2.1.0-M1
Java version: 1.6.0_13
Default locale: en_US, platform encoding: Cp1252
OS name: "windows vista" version: "6.0" arch: "x86" family: "windows".

i think i can succes compilation code through  by adding the below entry ,hope i will be usefull for you to debug .

i had used \<executable> and pint to javac .. no use in my case .

--- work around i found is below ---------------

\<plugin>
\<artifactId>maven-compiler-plugin\</artifactId>
\<configuration>
\<compilerId>eclipse\</compilerId>
\</configuration>
\<dependencies>
\<dependency>
\<groupId>org.codehaus.plexus\</groupId>
\<artifactId>plexus-compiler-eclipse\</artifactId>
\<version>1.5.1\</version>
\</dependency>
\</dependencies>
\</plugin>

Pls let me know if you need some more information .

i am using javaranch thread also for this issue : http://www.coderanch.com/t/437889/Ant-Maven-Other-Build-Tools/Maven-Compilation-Issue

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

The javac wrapper should be provided by the plugin dependency `org.codehaus.plexus:plexus-compiler-javac:jar:1.5.3:runtime`. Please check that the copy of this file (and its POM) in your local repository `~/.m2/repository/org/codehaus/plexus/plexus-compiler-javac/...` is intact and matches the [the files out on central](http://repo2.maven.org/maven2/org/codehaus/plexus/plexus-compiler-javac/1.5.3/).

**Comment by jira-importer** [comment]
**[Ganesh Gowtham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ganesh.gowtham)** commented

HI ,

i copied the jar from central repo and overrriden my local repo jar , after that every thing starts working fine .

Thanks a lot.
Ganesh Gowtham
