### ISSUE TITLE
[MCOMPILER-309] testCompile fails in 3.7.0 against Java 9 module 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#524]
**[Aleksandar Seovic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aseovic)** opened **[MCOMPILER-309](https://issues.apache.org/jira/browse/MCOMPILER-309?redirect=false)** and commented

When compiling Java 9 module, I get the following exception:

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project oracle.coherence.grpc.server: Execution default-testCompile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile failed: 29 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project oracle.coherence.grpc.server: Execution default-testCompile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile failed: 29
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-testCompile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile failed: 29
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 29
        at org.objectweb.asm.ClassReader.readUTF8(Unknown Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.readModule(Unknown Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.codehaus.plexus.languages.java.jpms.AsmModuleInfoParser.parse(AsmModuleInfoParser.java:81)
        at org.codehaus.plexus.languages.java.jpms.AsmModuleInfoParser.getModuleDescriptor(AsmModuleInfoParser.java:65)
        at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths(LocationManager.java:113)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.preparePaths(TestCompilerMojo.java:281)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:762)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:176)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

Switching to 3.6.2 allowed me to compile, so it seems like this was a regression in 3.7.0.

Based on the stack trace it looks like the failure is related to module info parsing, so I'm attaching my module_info.java as well.

---

**Affects:** 3.7.0

**Attachments:**
- [module-info.class](https://issues.apache.org/jira/secure/attachment/12889753/module-info.class) (_407 bytes_)
- [module-info.java](https://issues.apache.org/jira/secure/attachment/12889677/module-info.java) (_388 bytes_)

**Comment by jira-importer** [comment]
**[Aleksandar Seovic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aseovic)** commented

I was really hoping upgrading to ASM 6.0 would help, but no luck.

I'll file the issue with the ASM team and update this issue when I hear something. I've attached module_info.class to this issue as well, just to keep everything in one place.

Thanks.

**Comment by jira-importer** [comment]
**[Aleksandar Seovic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aseovic)** commented

Opened https://gitlab.ow2.org/asm/asm/issues/317794, and hoping for quick resolution. :-)

**Comment by jira-importer** [comment]
**[Aleksandar Seovic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aseovic)** commented

Argh... Sorry for distraction, I figured out what was going on...

One of the test frameworks I use has a transitive dependency on `cglib 3.2.5`, which has a transitive dependency on `ASM 6.0_ALPHA`, so that version was picked up by Maven instead of the one specified for the `maven-compiler-plugin`.

Once I excluded `cglib` from my dependencies everything worked fine, both with `ASM 6.0` and with whatever version is included by default with `maven-compiler-plugin`.

So, considering that the problem is not on your end, I'm gonna close this issue, but it's not bad to have it around as a reference, as others my run into the same problem. Did I mention that I hate `cglib` and the fact it is not shading ASM into it like everyone else? ;-)

**Comment by jira-importer** [comment]
**[Aleksandar Seovic](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aseovic)** commented

Looks like I don't have permissions to close the issue, so can someone please close it for me? Thanks.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Done so. Thanks for the feedback.

**Comment by jira-importer** [comment]
**[Luke Hutchison](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lukehutch)** commented

Adding the ASM 6.0 dependency fixed the issue for me. This is a common problem, based on the number of upvotes of this StackOverflow answer:

https://stackoverflow.com/a/49398936

maven-compiler-plugin has been in version 3.7.0 for a while now -- is there any chance a 3.7.1 could be pushed out that just bumps the ASM dependency version to 6.0?
