### ISSUE TITLE
[MCOMPILER-415] NullPointerException from javac when compiling AntlrWorks-Jank

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#634]
**[Andrew Janke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apjanke)** opened **[MCOMPILER-415](https://issues.apache.org/jira/browse/MCOMPILER-415?redirect=false)** and commented

I'm working on a project called AntlrWorks-Jank, an attempt to revive the defunct ANTLRWorks application. https://github.com/apjanke/antlrworks2-jank

When compiling the latest work-in-progress version of my code, I'm getting a NullPointerException apparently raised inside the javac code when it's called by the Maven Compiler Plugin.

```java
[antlrworks-jank] $ mvn -e compile
[INFO] Error stacktraces are turned on.
[...]
[INFO] works-editor-antlr4 ................................ FAILURE [  1.026 s]
[INFO] antlr-works-editor ................................. SKIPPED
[INFO] tvl-editor-whitespace .............................. SKIPPED
[INFO] works-editor-antlr3 ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.028 s
[INFO] Finished at: 2020-05-08T03:01:54-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project works-editor-antlr4: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project works-editor-antlr4: Fatal error compiling
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
[...]
Caused by: java.lang.NullPointerException
    at com.sun.tools.javac.main.JavaCompiler.readSourceFile (JavaCompiler.java:825)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete (JavacProcessingEnvironment.java:1510)
    at com.sun.tools.javac.code.Symbol.complete (Symbol.java:633)
    at com.sun.tools.javac.code.Symbol$ClassSymbol.complete (Symbol.java:1314)
    at com.sun.tools.javac.code.Type$ClassType.complete (Type.java:1139)
    at com.sun.tools.javac.code.Type$ClassType.getTypeArguments (Type.java:1065)
    at com.sun.tools.javac.code.Printer.visitClassType (Printer.java:237)
    at com.sun.tools.javac.code.Printer.visitClassType (Printer.java:52)
    at com.sun.tools.javac.code.Type$ClassType.accept (Type.java:992)
    at com.sun.tools.javac.code.Printer.visit (Printer.java:136)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument (AbstractDiagnosticFormatter.java:197)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments (AbstractDiagnosticFormatter.java:165)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage (BasicDiagnosticFormatter.java:111)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage (BasicDiagnosticFormatter.java:67)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument (AbstractDiagnosticFormatter.java:183)
    at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments (AbstractDiagnosticFormatter.java:165)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage (BasicDiagnosticFormatter.java:111)
    at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage (BasicDiagnosticFormatter.java:67)
    at com.sun.tools.javac.util.JCDiagnostic.getMessage (JCDiagnostic.java:771)
    at com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage (ClientCodeWrapper.java:799)
    at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess (JavaxToolsCompiler.java:149)
    at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile (JavacCompiler.java:169)
    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:785)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:129)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
```

The full code to reproduce is on the NPE-during-compile tag in that repo: https://github.com/apjanke/antlrworks2-jank/tree/NPE-during-compile.

I **think** I'm running the latest 3.8.1 version of maven-compiler-plugin, since I'm not specifying a version for it in my POMs. Seems to happen with Java 9, 11, and 13 (which I'm selecting by setting the $JAVA_HOME environment variable before running `mvn -e compile`).

Would this be a bug in maven-compiler-plugin? Or actually a bug in javac? Or something else?

Find output of `mvn -e compile &>antlrworks-jank-mvn-compile-NPE.log` and `mvn -X -e compile &>antlrworks-jank-mvn-compile-NPE-debug.log` attached.

---

**Affects:** 3.1

**Attachments:**
- [antlrworks-jank-mvn-compile-NPE.log](https://issues.apache.org/jira/secure/attachment/13002380/antlrworks-jank-mvn-compile-NPE.log) (_16.81 kB_)
- [antlrworks-jank-mvn-compile-NPE-02.log](https://issues.apache.org/jira/secure/attachment/13002417/antlrworks-jank-mvn-compile-NPE-02.log) (_16.83 kB_)
- [antlrworks-jank-mvn-compile-NPE-02-debug.log](https://issues.apache.org/jira/secure/attachment/13002416/antlrworks-jank-mvn-compile-NPE-02-debug.log) (_201.57 kB_)
- [antlrworks-jank-mvn-compile-NPE-debug.log](https://issues.apache.org/jira/secure/attachment/13002381/antlrworks-jank-mvn-compile-NPE-debug.log) (_229.60 kB_)

**Remote Links:**
- [JDK-8216202
](https://bugs.openjdk.java.net/browse/JDK-8216202)

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Output clearly shows you're not using with Maven Compiler 3.8.1, but with 3.1: see `org.apache.maven.plugins:maven-compiler-plugin:3.1:compile`.
You should at least lock the version of the plugin.

**Comment by jira-importer** [comment]
**[Andrew Janke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apjanke)** commented

Thanks! I'll report my repro up there. Can you close this out as not-a-Maven-Compiler-Plugin-bug?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I'll cross link the issues. In case the conclusion is that Maven Compiler Plugin does something wrong, we can reopen it.

**Comment by jira-importer** [comment]
**[Dan Berindei](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.berindei)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) As the latest comment on [JDK-8216202](https://bugs.openjdk.java.net/browse/JDK-8216202?focusedCommentId=14438100&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14438100) suggests, this could be fixed in `JavaxToolsCompiler`
by using a custom `DiagnosticListener` that calls `Diagnostic.getMessage()` eagerly.

I still think it's a bug in `JavaCompiler`, because the [javadoc](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/tools/JavaCompiler.html) contains an example using `DiagnosticCollector` exactly the same way `JavaxToolsCompiler` does it, but I don't have an account there so I can't comment on it.

The root cause is that both `JavaCompiler` and `JavacTaskImpl` call `JavaCompiler.close()` before returning:

```
at com.sun.tools.javac.main.JavaCompiler.close(JavaCompiler.java:1782)
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:997)
at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
at com.sun.tools.javac.api.JavacTaskImpl$$Lambda$270.379623433.call(Unknown Source:-1)
at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
```

```
at com.sun.tools.javac.main.JavaCompiler.close(JavaCompiler.java:1782)
at com.sun.tools.javac.api.JavacTaskImpl.cleanup(JavacTaskImpl.java:229)
at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:109)
at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
```

`JavaxToolsCompiler` later calls `getMessage()` on a diagnostic message that references an unresolved class,
and `ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage()` ends up calling `JavaCompiler.readSourceFile()`
to resolve the generic type arguments of the unresolved class.
But the `JavaCompiler` instance has been closed and all the fields are now set to `null`,
so `readSourceFile()` fails with a `NullPointerException`

```
at com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:841)
at com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1530)
at com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
at com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
at com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
at com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
at com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:993)
at com.sun.tools.javac.code.Printer.visit(Printer.java:136)
at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:199)
at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:185)
at com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
at com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
at com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:788)
at com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:131)
at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
```

FWIW I haven't been able to reproduce this with a simple project.
However, I can reproduce it reliably with:

```
git clone https://github.com/debezium/debezium
cd debezium
git checkout 8f717785b2d651ea5f8bbd0aaabb85562e1ef70b
mvn clean compile -am -pl debezium-connector-oracle -Poracle,infinispan-buffer
```

Module `debezium-connector-oracle` only builds when the `oracle` profile is active,
and the proprietary dependency that allows class `XStreamChangeRecordEmitter` to compile is referenced only in some profiles (e.g. `assembly`).
Other profiles (e.g. `oracle-ci`) use the `maven-compiler-plugin` to exclude the problematic class from compilation, and yet others (i.e. the 2 on the command line) don't do anything about it, so the compilation should fail with errors

```
26 = {CompilerMessage@6837} "/home/dan/Work/debezium/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrPosition.java:[18,22] package oracle.streams does not exist"
 27 = {CompilerMessage@6838} "/home/dan/Work/debezium/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrPosition.java:[19,22] package oracle.streams does not exist"
 28 = {CompilerMessage@6839} "/home/dan/Work/debezium/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamChangeRecordEmitter.java:[16,22] package oracle.streams does not exist"
 29 = {CompilerMessage@6840} "/home/dan/Work/debezium/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamChangeRecordEmitter.java:[17,22] package oracle.streams does not exist"
 30 = {CompilerMessage@6841} "/home/dan/Work/debezium/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamChangeRecordEmitter.java:[24,73] cannot find symbol\n  symbol: class ColumnValue"
```

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This is not a maven-compiler-plugin bug, but a JDK bug. Nothing the plugin can do to fix it.

**Comment by jira-importer** [comment]
**[Dan Berindei](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.berindei)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) I agree with your assessment that it's a JDK bug, but I don't agree with the "Nothing the plugin can do to fix it" part. In fact, I suggested a workaround in my comment.

Considering that the JDK team doesn't seem to consider it a JDK bug, and we have no idea if JDK-8216202 will ever be fixed, I think putting the workaround in maven-compiler-plugin would be quite reasonable.

**Comment by jira-importer** [comment]
**[Vincent Latombe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vlatombe)** commented

I'm commenting here in the hope that someone from the JDK sees this

I think the problem was introduced in openjdk due to this commit https://github.com/openjdk/jdk/commit/e5c81018946876d91f89a10999d3582eb592c340#diff-e4e91210bdddd5366d98b565bcb74c4e7d1ed85adaa5045541822c3bb10589dcR906-R908

It is closing the JavaCompiler object implicitly once the compilation is done. However the resulting Diagnostic objects (obtained by [plexus-compiler-api](https://github.com/codehaus-plexus/plexus-compiler/blob/4291bb706b9e3e27eb0c24cc547f248073e8819a/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavaxToolsCompiler.java#L116-L138) legally using what is documented in https://docs.oracle.com/javase/8/docs/api/javax/tools/JavaCompiler.html) still holds references that can be resolved only once the compilation task is done.

**Comment by jira-importer** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

[Vincent Latombe](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vlatombe) This issue is resolved for me by backporting [openjdk/jdk@`{}44ae643b2b4{`}](https://github.com/openjdk/jdk/commit/44ae643b2b49b66b1fff4c151c17972c6b683cc0) to `jdk11u-dev` as in [openjdk/jdk11u-dev#919](https://github.com/openjdk/jdk11u-dev/pull/919).

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

recent changes in plexus-compiler will ignore most of possible issues due to jdk compiler potential similar buhs see https://github.com/codehaus-plexus/plexus-compiler/commit/26f80882b787a7dbe949649295c0e27e02079f14

**Comment by jira-importer** [comment]
**[Basil Crow](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=basil)** commented

The fix for the underlying OpenJDK issue has been backported to `jdk11u-dev` in [openjdk/jdk11u-dev#919](https://github.com/openjdk/jdk11u-dev/pull/919) toward OpenJDK 11.0.16, currently scheduled for a July 2022 GA.
