### ISSUE TITLE
[MCOMPILER-538] Do not add target/generated-sources/annotations to the source roots

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#744]
**[Daniel Mensinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER281729)** opened **[MCOMPILER-538](https://issues.apache.org/jira/browse/MCOMPILER-538?redirect=false)** and commented

Adding the generated source root (`target/generated-sources/annotations`) is not required for javac. Additionally adding the generated source root results in compilation errors with annotation processors generating code unless the generated-sources dir is cleaned.

Specifically, the following steps result in compilation errors:
1. run `mvn clean`
2. Modify a source file that is consumed by the annotation processor so that there is a compilation error, but the annotation processor still runs (add or remove a parameter in a method call).
3. run `mvn compile` --> the generated file exists but there is no class file for the source file.
4. Fix the "bug" from step 2
5. run `mvn compile` again --> compilation should succeed, but it fails.

---

Example code: https://github.com/mensinda/quarkus-stuff/tree/annotationProcessingTest

Use the `annotationProcessingTest` branch!

For step 2 this change can be used:

```java
diff --git a/code/src/main/java/bar/MyAnnotatedClass.java b/code/src/main/java/bar/MyAnnotatedClass.java
index bbfef7a..a303924 100644
--- a/code/src/main/java/bar/MyAnnotatedClass.java
+++ b/code/src/main/java/bar/MyAnnotatedClass.java
@@ -4,7 +4,7 @@ import foo.MyAnnotation;

 @MyAnnotation
 public class MyAnnotatedClass {
-    MyGeneratedClass generatedClass = new MyGeneratedClass();
+    MyGeneratedClass generatedClass = new MyGeneratedClass(false);

     // foo

```

 
To see that **not** adding `target/generated-sources/annotations` helps run `mvn -X compile` and copy the `Command line options:`. Then run `javac` manually, but remove the `target/generated-sources/annotations` from the `-sourcepath` list, but **not** the `-s` parameter.

---

PR with a fix: https://github.com/apache/maven-compiler-plugin/pull/191

---

**Affects:** 3.11.0

**Issue Links:**
- [MCOMPILER-540](https://issues.apache.org/jira/browse/MCOMPILER-540) useIncrementalCompilation=false may add generated sources to the sources list

- [MCOMPILER-333](https://issues.apache.org/jira/browse/MCOMPILER-333) Incremental compilation causes "mvn clean compile compile" to fail

**Remote Links:**
- [GitHub Pull Request #191
](https://github.com/apache/maven-compiler-plugin/pull/191)

2 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Jorge Solórzano](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jorsol)** commented

This PR requires a test to ensure it actually fixes the bug.

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

generated-sources will be removed https://github.com/apache/maven-compiler-plugin/pull/214

**Comment by jira-importer** [comment]
**[zosrothko](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zosrothko)** commented

Hello

I do not have any annotation in a small multmodule maven project and the error below is blocking the full maven rebuild

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.0:testCompile (default-testCompile) on project entitymodule: Fatal error compiling: basedir C:\MXW\Clients\SwissLife\ArchieV3\DEV\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations does not exist -> [Help 1]
[E

Below the javac command line from: mvn clean install -X

[DEBUG] Using compiler 'javac'.
[DEBUG] Adding C:\MXW\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations to test-compile source roots:
  C:\MXW\Modules\multimodulemavenproject\entitymodule\src\test\java
[DEBUG] New test-compile source roots:
  C:\MXW\Modules\multimodulemavenproject\entitymodule\src\test\java
  C:\MXW\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO]  New dependency detected: C:\MXW\Modules\multimodulemavenproject\entitymodule\target\classes\com\baeldung\entity\User.class
[INFO] Recompiling the module because of changed dependency.
[DEBUG] Classpath:
[DEBUG]  C:\MXW\Modules\multimodulemavenproject\entitymodule\target\test-classes
[DEBUG] Modulepath:
[DEBUG]  C:\MXW\Modules\multimodulemavenproject\entitymodule\target\classes
[DEBUG] Source roots:
[DEBUG]  C:\MXW\Modules\multimodulemavenproject\entitymodule\src\test\java
[DEBUG]  C:\MXW\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations
[DEBUG] Command line options:
[DEBUG] -d C:\MXW\Modules\multimodulemavenproject\entitymodule\target\test-classes 
-classpath C:\MXW\Modules\multimodulemavenproject\entitymodule\target\test-classes; 
--module-path C:\MXW\Modules\multimodulemavenproject\entitymodule\target\classes; 
-sourcepath C:\MXW\Modules\multimodulemavenproject\entitymodule\src\test\java;C:\MXW\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations;
 -s C:\MXW\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations
 -g --release 11 -encoding UTF-8 
 --patch-module com.baeldung.entitymodule=C:\MXW\Modules\multimodulemavenproject\entitymodule\target\classes;C:\MXW\Modules\multimodulemavenproject\entitymodule\src\test\java;C:\MXW\Modules\multimodulemavenproject\entitymodule\target\generated-test-sources\test-annotations;
 --add-reads com.baeldung.entitymodule=ALL-UNNAMED
 -XDuseUnsharedTable=true

**Comment by jira-importer** [comment]
**[Slawomir Jaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=slawekjaranowski)** commented

[mensinda](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mensinda) I have tested your patch with provided project .... and I have:

```
generatedSourcesInJavacArgs.sh

...

[INFO] --- compiler:3.12.1-SNAPSHOT:compile (default-compile) @ code ---
[INFO] Compiling 2 source files with javac [forked debug deprecation target 17] to target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] [options] system modules path not set in conjunction with -source 17
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] java.lang.RuntimeException: javax.annotation.processing.FilerException: Attempt to recreate a file for type bar.MyGeneratedClass
	at foo.MyProcessor.process(MyProcessor.java:24)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1021)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:937)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1265)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1380)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1272)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:319)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
Caused by: javax.annotation.processing.FilerException: Attempt to recreate a file for type bar.MyGeneratedClass
	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:741)
	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:498)
	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:435)
	at foo.MyProcessor.generate(MyProcessor.java:40)
	at foo.MyProcessor.process(MyProcessor.java:22)
	... 10 more
```

So looks like not resolve a problem

We should have an IT - which can reproduce a problem

**Comment by jira-importer** [comment]
**[Daniel Mensinger](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=JIRAUSER281729)** commented

[sjaranowski](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=sjaranowski): The `generatedSourcesInJavacArgs.sh` script is for MCOMPILER-540 and cannot be used to reproduce the bug.

It took me a while, but there is a test case now in the PR.
