### ISSUE TITLE
[MCOMPILER-217] IT failure with Jdk 8 (EA)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#835]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** opened **[MCOMPILER-217](https://issues.apache.org/jira/browse/MCOMPILER-217?redirect=false)** and commented

see https://builds.apache.org/view/M-R/view/Maven/job/maven-plugins-ITs-m3.1.x-with-maven-plugin-jdk-1.8/modules

```
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 18, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  error-prone-compiler/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

```
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:789)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
       Caused by: java.lang.ClassCastException: com.sun.tools.javac.main.Main$Result cannot be cast to java.lang.Integer
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.compileInProcessWithProperClassloader(JavacCompilerWithErrorProne.java:180)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:538)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:778)
        ... 22 more
```

---

**Affects:** 3.1

**Issue Links:**
- [MNG-5551](https://issues.apache.org/jira/browse/MNG-5551) check that everything compile and run fine with Java 8

1 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This is something which has to be fixed in [plexus-compiler-javac-errorprone](https://github.com/sonatype/plexus-compiler/blob/master/plexus-compilers/plexus-compiler-javac-errorprone/src/main/java/org/codehaus/plexus/compiler/javac/errorprone/JavacCompilerWithErrorProne.java), probably with help from [Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy) or [Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold) who have at least commit rights on this project.

**Comment by jira-importer** [comment]
**[Kristian Rosenvold](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=krosenvold)** commented

The MCOMPiLER217 branch in plexus-compilers seem to indicate that the error-prone compiler has trouble with jdk8. The IT still fails, but now for a different reason

**Comment by jira-importer** [comment]
**[Olivier Lamy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=olamy)** commented

for some reason, error prone doesn't generate anymore error/warnings with 1.8

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Current trunk in SVN r1745932 works without any issue.
