### ISSUE TITLE
[MCOMPILER-196] test compilation during site generation failed - cobertura plugin seems to be the bad guy :)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-compiler-plugin#847]
**[Andreas Höhmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ahoehma)** opened **[MCOMPILER-196](https://issues.apache.org/jira/browse/MCOMPILER-196?redirect=false)** and commented

```
$ mvn clean site:site
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hscm-vaadin 2.2013.02.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ hscm-vaadin ---
[INFO] Deleting D:\DEV\git-repos\spice-hscm\target
[INFO]
[INFO] --- maven-site-plugin:3.2:site (default-cli) @ hscm-vaadin ---
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.6
[INFO] configuring report plugin org.apache.maven.plugins:maven-changes-plugin:2.8
[INFO] configuring report plugin org.apache.maven.plugins:maven-surefire-report-plugin:2.12.4
[INFO]
[INFO] >>> maven-surefire-report-plugin:2.12.4:report-only (report:report-only) @ hscm-vaadin >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create-timestamp (default) @ hscm-vaadin ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create (create-buildNumber) @ hscm-vaadin ---
[INFO] Storing buildNumber: 20130103 at timestamp: 1357222836233
[INFO] Executing: cmd.exe /X /C "svn --non-interactive info"
[INFO] Working directory: D:\DEV\git-repos\spice-hscm
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-banned-logging-dependencies) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-jdk-version) @ hscm-vaadin ---
[INFO]
[INFO] <<< maven-surefire-report-plugin:2.12.4:report-only (report:report-only) @ hscm-vaadin <<<
[INFO] configuring report plugin org.apache.maven.plugins:maven-jxr-plugin:2.3
[INFO] configuring report plugin org.codehaus.mojo:taglist-maven-plugin:2.4
[INFO] configuring report plugin org.codehaus.mojo:jdepend-maven-plugin:2.0-beta-2
[INFO]
[INFO] >>> jdepend-maven-plugin:2.0-beta-2:generate (report:generate) @ hscm-vaadin >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create-timestamp (default) @ hscm-vaadin ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create (create-buildNumber) @ hscm-vaadin ---
[INFO] Storing buildNumber: 20130103 at timestamp: 1357222837029
[INFO] Executing: cmd.exe /X /C "svn --non-interactive info"
[INFO] Working directory: D:\DEV\git-repos\spice-hscm
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-banned-logging-dependencies) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-jdk-version) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-jaxb21-plugin:0.8.2:generate (generate-gfx-customization-sources) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-jaxb21-plugin:0.8.2:generate (generate-plugin-customization-sources) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hscm-vaadin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 65 resources
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ hscm-vaadin ---
[INFO] Compiling 590 source files to D:\DEV\git-repos\spice-hscm\target\classes
[INFO]
[INFO] --- aspectj-maven-plugin:1.4:compile (default) @ hscm-vaadin ---
[WARNING] advice defined in org.springframework.orm.jpa.aspectj.JpaExceptionTranslatorAspect has not been applied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect has not been applied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.springframework.mock.staticmock.AnnotationDrivenStaticEntityMockingControl has not been applied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.springframework.mock.staticmock.AbstractMethodMockingControl has not been applied [Xlint:adviceDidNotMatch]
[WARNING] advice defined in org.springframework.mock.staticmock.AbstractMethodMockingControl has not been applied [Xlint:adviceDidNotMatch]
[INFO]
[INFO] <<< jdepend-maven-plugin:2.0-beta-2:generate (report:generate) @ hscm-vaadin <<<
[INFO] configuring report plugin org.codehaus.mojo:javancss-maven-plugin:2.0
[INFO] configuring report plugin org.apache.maven.plugins:maven-javadoc-plugin:2.9
[INFO]
[INFO] >>> maven-javadoc-plugin:2.9:javadoc (report:javadoc) @ hscm-vaadin >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create-timestamp (default) @ hscm-vaadin ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create (create-buildNumber) @ hscm-vaadin ---
[INFO] Storing buildNumber: 20130103 at timestamp: 1357222854538
[INFO] Executing: cmd.exe /X /C "svn --non-interactive info"
[INFO] Working directory: D:\DEV\git-repos\spice-hscm
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-banned-logging-dependencies) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-jdk-version) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-jaxb21-plugin:0.8.2:generate (generate-gfx-customization-sources) @ hscm-vaadin ---
[INFO] Skipped XJC execution. Generated sources were up-to-date.
[INFO]
[INFO] --- maven-jaxb21-plugin:0.8.2:generate (generate-plugin-customization-sources) @ hscm-vaadin ---
[INFO] Skipped XJC execution. Generated sources were up-to-date.
[INFO]
[INFO] <<< maven-javadoc-plugin:2.9:javadoc (report:javadoc) @ hscm-vaadin <<<
[INFO] configuring report plugin org.apache.maven.plugins:maven-checkstyle-plugin:2.9.1
[INFO] configuring report plugin org.codehaus.mojo:findbugs-maven-plugin:2.5.2
[INFO] configuring report plugin org.codehaus.mojo:cobertura-maven-plugin:2.5.2
[INFO]
[INFO] >>> cobertura-maven-plugin:2.5.2:cobertura (report:cobertura) @ hscm-vaadin >>>
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create-timestamp (default) @ hscm-vaadin ---
[INFO]
[INFO] --- buildnumber-maven-plugin:1.1:create (create-buildNumber) @ hscm-vaadin ---
[INFO] Storing buildNumber: 20130103 at timestamp: 1357222856020
[INFO] Executing: cmd.exe /X /C "svn --non-interactive info"
[INFO] Working directory: D:\DEV\git-repos\spice-hscm
[INFO] Storing buildScmBranch: UNKNOWN_BRANCH
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-banned-logging-dependencies) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.1:enforce (enforce-jdk-version) @ hscm-vaadin ---
[INFO]
[INFO] --- maven-jaxb21-plugin:0.8.2:generate (generate-gfx-customization-sources) @ hscm-vaadin ---
[INFO] Skipped XJC execution. Generated sources were up-to-date.
[INFO]
[INFO] --- maven-jaxb21-plugin:0.8.2:generate (generate-plugin-customization-sources) @ hscm-vaadin ---
[INFO] Skipped XJC execution. Generated sources were up-to-date.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hscm-vaadin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 65 resources
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ hscm-vaadin ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- aspectj-maven-plugin:1.4:compile (default) @ hscm-vaadin ---
[INFO] No modifications found skipping aspectJ compile
[INFO]
[INFO] --- cobertura-maven-plugin:2.5.2:instrument (report:cobertura) @ hscm-vaadin ---
[INFO] Cobertura 1.9.4.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
Instrumenting 1113 files to D:\DEV\git-repos\spice-hscm\target\generated-classes\cobertura
Cobertura: Saved information on 1113 classes.
Instrument time: 1935ms

[INFO] Instrumentation was successful.
[INFO] NOT adding cobertura ser file to attached artifacts list.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ hscm-vaadin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 57 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ hscm-vaadin ---
[INFO] Compiling 70 source files to D:\DEV\git-repos\spice-hscm\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
An exception has occurred in the compiler (1.6.0_38). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug
 Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.NullPointerException
        at com.sun.tools.javac.code.Symbol$MethodSymbol.params(Symbol.java:1196)
        at com.sun.tools.javac.jvm.ClassReader.attachParameterAnnotations(ClassReader.java:1111)
        at com.sun.tools.javac.jvm.ClassReader.readMemberAttr(ClassReader.java:871)
        at com.sun.tools.javac.jvm.ClassReader.readMemberAttrs(ClassReader.java:1027)
        at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:1490)
        at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:1586)
        at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:1658)
        at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:1845)
        at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:1777)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
        at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
        at com.sun.tools.javac.jvm.ClassReader.loadClass(ClassReader.java:1951)
        at com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:867)
        at com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:1036)
        at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:1921)
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:1835)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1522)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
        at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:527)
        at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:495)
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:387)
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:399)
        at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:512)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:446)
        at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:387)
        at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:819)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
        at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
        at com.sun.tools.javac.comp.Enter.complete(Enter.java:464)
        at com.sun.tools.javac.comp.Enter.main(Enter.java:442)
        at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:822)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
        at com.sun.tools.javac.main.Main.compile(Main.java:353)
        at com.sun.tools.javac.main.Main.compile(Main.java:279)
        at com.sun.tools.javac.main.Main.compile(Main.java:270)
        at com.sun.tools.javac.Main.compile(Main.java:87)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:554)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:161)
        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:605)
        at org.apache.maven.plugin.TestCompilerMojo.execute(TestCompilerMojo.java:161)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeForkedExecutions(DefaultLifecycleExecutor.java:173)
        at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildReportPlugin(DefaultMavenReportExecutor.java:284)
        at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildMavenReports(DefaultMavenReportExecutor.java:150)
        at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getReports(AbstractSiteRenderingMojo.java:235)
        at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:121)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.771s
[INFO] Finished at: Thu Jan 03 15:21:03 CET 2013
[INFO] Final Memory: 53M/137M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.2:site (default-cli) on project hscm-vaadin: failed to get report for org.codehaus.mojo:cobe
rtura-maven-plugin: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project hscm-vaadin: Compilation fa
ilure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] An exception has occurred in the compiler (1.6.0_38). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking
 the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
[ERROR] java.lang.NullPointerException
[ERROR] at com.sun.tools.javac.code.Symbol$MethodSymbol.params(Symbol.java:1196)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.attachParameterAnnotations(ClassReader.java:1111)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.readMemberAttr(ClassReader.java:871)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.readMemberAttrs(ClassReader.java:1027)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:1490)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:1586)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:1658)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.fillIn(ClassReader.java:1845)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.complete(ClassReader.java:1777)
[ERROR] at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
[ERROR] at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
[ERROR] at com.sun.tools.javac.jvm.ClassReader.loadClass(ClassReader.java:1951)
[ERROR] at com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:867)
[ERROR] at com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:1036)
[ERROR] at com.sun.tools.javac.comp.Attr.selectSym(Attr.java:1921)
[ERROR] at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:1835)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1522)
[ERROR] at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:360)
[ERROR] at com.sun.tools.javac.comp.MemberEnter.visitImport(MemberEnter.java:527)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:495)
[ERROR] at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:387)
[ERROR] at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:399)
[ERROR] at com.sun.tools.javac.comp.MemberEnter.visitTopLevel(MemberEnter.java:512)
[ERROR] at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:446)
[ERROR] at com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:387)
[ERROR] at com.sun.tools.javac.comp.MemberEnter.complete(MemberEnter.java:819)
[ERROR] at com.sun.tools.javac.code.Symbol.complete(Symbol.java:384)
[ERROR] at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:766)
[ERROR] at com.sun.tools.javac.comp.Enter.complete(Enter.java:464)
[ERROR] at com.sun.tools.javac.comp.Enter.main(Enter.java:442)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:822)
[ERROR] at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:727)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:353)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:279)
[ERROR] at com.sun.tools.javac.main.Main.compile(Main.java:270)
[ERROR] at com.sun.tools.javac.Main.compile(Main.java:87)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:597)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:554)
[ERROR] at org.codehaus.plexus.compiler.javac.JavacCompiler.compile(JavacCompiler.java:161)
[ERROR] at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:605)
[ERROR] at org.apache.maven.plugin.TestCompilerMojo.execute(TestCompilerMojo.java:161)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:365)
[ERROR] at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeForkedExecutions(DefaultLifecycleExecutor.java:173)
[ERROR] at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildReportPlugin(DefaultMavenReportExecutor.java:284)
[ERROR] at org.apache.maven.reporting.exec.DefaultMavenReportExecutor.buildMavenReports(DefaultMavenReportExecutor.java:150)
[ERROR] at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getReports(AbstractSiteRenderingMojo.java:235)
[ERROR] at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:121)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:597)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

---

**Affects:** 2.3.2, 2.5.1

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Not enough information to reproduce. If `compiler:testCompile` does succeed, it is very likely that this is indeed a cobertura issue, nothing the maven-compiler-plugin can do here.
